# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Copyright © 2023 Probably Yes Software LLC - CC-BY-SA-4.0           ┃
# ┃ Author: Conner Blair <conner@probablyyes.software>                  ┃
# ┠─────────────────────────────────────────────────────────────────────┨
# ┃ This library is made available for public use under the             ┃
# ┃ Creative Commons Attribution Share Alike 4.0 International license. ┃
# ┃ See the top level file 'LICENSE' for more information.              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

[registries.crates-io]
protocol = "sparse"

[profile.release]
lto = true

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
